[package]
name = "astra-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
feed-rs = "2.3"
ammonia = "4"
html-escape = "0.2"
tracing.workspace = true
domain.workspace = true
sqlx.workspace = true
deadpool-redis.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio.workspace = true
chrono.workspace = true
uuid.workspace = true
anyhow.workspace = true
url.workspace = true

base64.workspace = true
sha3.workspace = true
application.workspace = true

[dev-dependencies]
axum.workspace = true
